services:
  terminusdb:
    image: terminusdb/terminusdb-server:latest
    container_name: terminusdb-equipment
    ports:
      - "6363:6363"
    environment:
      - TERMINUSDB_ADMIN_PASS=root
    volumes:
      - terminusdb-data:/app/terminusdb/storage

volumes:
  terminusdb-data:
